# See https://pre-commit.com for more information

files: .*\.py$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: settings\.py
      - id: end-of-file-fixer
      - id: check-added-large-files
        files: ""
      - id: debug-statements
        files: .*\.py$
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: 
          - --fix 
      - id: ruff-format
