[project]
name = "dexscript"
version = "1.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.5.0",
    "django>=5.2.8",
    "mkdocs-material>=9.7.0",
    "packaging>=25.0",
    "pytest>=9.0.1",
    "python-dateutil>=2.9.0.post0",
    "tortoise-orm>=0.25.1",
]

[dependency-groups]
dev = [
    "django-types>=0.22.0",
    "pygments>=2.19.2",
    "ruff>=0.14.6",
    "mypy>=1.19.0",
    "types-python-dateutil>=2.9.0.20251115",
]

[tool.dexi]
public = true
ballsdex-version = ">=2.22.0"
include-license = true

[tool.dexi.package]
source = "package"
target = "dexscript"

[tool.ruff]
line-length = 99
indent-width = 4
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = true

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["ballsdex"]
split-on-trailing-comma = false

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["F401"]

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning:discord.*"]

[tool.setuptools]
packages = ["plugin"]

[project.entry-points."mkdocs.plugins"]
dexscript = "plugin.plugin:DexScriptPlugin"

[project.entry-points."pygments.lexers"]
dexscript = "plugin.lexer:DexScriptLexer"
