[project]
name = "dexscript"
version = "1.0"
description = ""
requires-python = ">=3.12"
license = "MIT"
dependencies = [
    "discord.py>=2.5.0",
    "ruff>=0.11.13"
]

[tool.dexi]
requires-ballsdex = ">=2.22.0"

[tool.ruff]
line-length = 99
lint.ignore = ["E203", "F704", "F706", "F821"]
lint.extend-select = ["E501", "I001"]
