name: Bug Report
description: Report a DexScript bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a DexScript bug!
  - type: checkboxes
    attributes:
      label: Error Page
      description: The [error page](https://github.com/Dotsian/DexScript/wiki/Errors) explains what common errors mean and how to solve them.
      options:
        - label: Did you read the error page and view the common errors?
          required: true
  - type: dropdown
    id: location
    attributes:
      label: Bug Location
      description: Where did this bug occur? If you select "Other", please specify in the Bug Description section.
      options:
        - While installing.
        - While updating.
        - While uninstalling.
        - When running a command.
        - When trying to run a command.
        - When using a text command, such as ".about" or ".installer".
        - When trying to turn on the bot.
        - Other (please specify in the Bug Description section)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Explain the bug and what happened before it appeared.
      placeholder: Bug explanation...
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: Add your version number here. You can fetch it using the `.about` command.
      placeholder: Version number...
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What fork are you using?
      options:
        - Ballsdex
        - CarFigures
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: If there was an error, paste it below.
      render: shell
