# Define DexScript methods here.
METHODS = [
    "CREATE",
    "DELETE",
    "EDIT",
    "UPDATE",
    "VIEW",
]

# Define common models here.
MODELS = [
    "BALL",
    "REGIME",
    "SPECIAL",
    "BALL-INSTANCE",
    "ECONOMY",
    "PLAYER",
    "GUILD-CONFIG",
    "BLACKLISTED-ID",
    "BLACKLISTED-GUILD",
    "FRIENDSHIP",
    "TRADE",
    "TRADE-OBJECT",
    "BLOCK"
]

# Define common attributes here.
ATTRIBUTES = [
    "ID",
    "COUNTRY",
    "HEALTH",
    "ATTACK",
    "RARITY",
    "EMOJI_ID",
    "WILD_CARD",
    "COLLECTION_CARD",
    "CREDITS",
    "CAPACITY_NAME",
    "CAPACITY_DESCRIPTION",
    "CAPACITY_LOGIC",
    "ENABLED",
    "SHORT_NAME",
    "CATCH_NAMES",
    "TRADEABLE",
    "ECONOMY",
    "REGIME",
    "CREATED_AT",
    "TRANSLATIONS",
    "NAME",
    "BACKGROUND",
    "ICON",
    "CATCH_PHRASE",
    "START_DATE",
    "END_DATE",
    "EMOJI",
    "HIDDEN",
    "DISCORD_ID",
    "MONEY",
    "DONATION_POLICY",
    "PRIVACY_POLICY",
    "MENTION_POLICY",
    "FRIEND_POLICY",
    "TRADE_COOLDOWN_POLICY",
    "GUILD_ID",
    "SPAWN_CHANNEL",
    "SILENT",
    "REASON",
    "DATE",
    "MODERATOR_ID",
    "PLAYER1",
    "PLAYER",
    "TRADE",
    "SINCE",
    "PLAYER2",
]
