# Whether or not DexScript will warn you for running an outdated version.
version-warning = true

# The command groups that DexScript will load.
command-groups = ["Global", "Emoji", "Eval", "File", "Filter", "Template"]

# Displays additional information for error handling.
debug = false

# The GitHub branch that will be used for version checking and other misc features.
branch = "main"
