# The name of your package.
name: My Package

# The package version.
version: 0.1

# The description of the package.
description: >
  This is a `package.yml` example file!

# The package creator
author: dot_zz

# The logo URL that represents your package. (OPTIONAL)
logo: https://i.imgur.com/uKfx0qO.png

# The primary hex color that represents your package. (OPTIONAL)
color: 03BAFC

# Determines if you need to restart the bot for your package to work.
restart: false

# The forks your package supports.
supported:
  - ballsdex
  - carfigures

# All files that will be created when the package is installed.
files:
  - __init__.py
  - cog.py

# Migrations that will be ran when the package is installed.
# Useful for making changes to files without directly replacing them.
# $DIR is either `ballsdex` or `carfigures` depending on what you use.
# For inline, use the /- phrase. For a new line, use the -n phrase instead of \n.
# To seperate code for the upgrade migration, use the || symbols.

# Upgrade will add code underneath of another line of code.
# Drop will remove a line of code.
migrations:
  - $DIR/core/bot.py:
    - Upgrade:
        - import types || import os -n
    - Drop:
        - /-from $DIR.core.dexscript import DexScript -n