name: docs
on:
  push:
    branches:
      - "1.0"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Install dependencies
        run: uv sync --locked
      - name: Install plugin
        run: uv pip install -e .
      - run: uv run mkdocs gh-deploy --force